name: Build WebAssembly Module

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 4.0.13

    - name: Compile project
      run: |
        chmod +x compile.sh
        ./compile.sh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: soundfont-module
        path: |
          soundfont.js
          soundfont.wasm
          
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          soundfont.js
          soundfont.wasm